### PR TITLE
Navigation

### PR DESCRIPTION
**Pull request by dunncl15**
@Riizu @NickyBobby 

I've added basic routing functionality for the navigation links along with some preliminary styling for the menu/navigation. Below are a couple screen shots of where things are at. Let me know if you have any questions/concerns. Thanks.

**Route: New Page** 
screen shot 2017-04-10 at 7 15 33 pm

**Route: All Pages**
screen shot 2017-04-10 at 7 15 45 pm

### CODE REVIEW

**Comment by NickyBobby** [comment]
This looks really great so far! I like the screenshots! One thing to keep in mind though is these components are a part of the admin dashboard so these views will be under the admin namespace.  For example, `/admin/new-page` and `/admin/pages`. I don't think it's necessary to change it for this PR but will need to be adjusted soon. Other than that I think everything looks great!

Did you have any other thoughts, @Riizu ?

**Comment by dunncl15** [comment]
Good point thanks @NickyBobby . I'll be sure to update all the paths to reflect the admin namespace going forward.

**Comment by rgbatty** [comment]
Looks great! 😄 I definitely agree with @NickyBobby , but other than that, looks good. I haven't had a chance to look over the code yet, but I will probably with the first iteration of the page implementation.

**Comment by rgbatty** [comment]
Is this ready to be merged?

**Comment by NickyBobby** [comment]
Looks GTM to me 👍

**Pull request merged**
