### PR TITLE
App styling

### PR DESCRIPTION
**Pull request by dunncl15**
@Riizu @NickyBobby 

This PR includes everything discussed today. Below are a series of screenshots to show you how things are looking. Let me know if you have any questions/concerns. Thanks!

**Admin View**
All Pages:
screen shot 2017-04-17 at 8 38 10 pm

Create Page:
screen shot 2017-04-17 at 8 38 28 pm

Edit Page:
screen shot 2017-04-17 at 8 38 42 pm

**Client Facing**
screen shot 2017-04-17 at 8 39 06 pm

### CODE REVIEW

**Comment by rgbatty** [comment]
Is this meant to be merged into master or was that a goof and its meant for develop?

**Comment by dunncl15** [comment]
That was a goof @Riizu . Changing it now.

**Comment by Riizu** [comment]
Thats alright. You can actually just change the base branch for this PR. I'll do it now.

In other news, I really like these style changes!

**Comment by dunncl15** [comment]
@Riizu should I close this PR and open a new one or is there a way to change the base branch?

**Comment by rgbatty** [comment]
Changed it for you :smile:

**Comment by dunncl15** [comment]
thanks!

**Comment by rgbatty** [comment]
Is this number of commits accurate? (80+)

**Comment by dunncl15** [comment]
Indeed @Riizu .

**Comment by rgbatty** [comment]
Oh! Did the previous PR not get merged into develop? Im seeing commits as old as April 12th.

**Comment by dunncl15** [comment]
Yeah the user-navigation PR never got merged so I branched off that and carried everything forward with this branch. @Riizu

**Comment by rgbatty** [comment]
Ah awesome. All of this looks great. I'll merge this now.

**Pull request merged**
