### PR TITLE
Refactor redux store to only include pages array instead an additional userNav array

### PR DESCRIPTION
**Pull request by dunncl15**
@Riizu @NickyBobby 

I did some refactoring to simplify things a bit further. I removed the userNav array altogether so now everything is rendered via the pages array. It cuts down on some of the logic in the helper file for the AdminPageCard, which was a little hacky previously.

Let me know what you think when you have a chance.

Also, I'm looking into implementing a preview feature. I'm thinking of using the [react-modal](https://www.npmjs.com/package/react-modal) package which creates a pretty cool overlay that would allow the admin user to see the page component prior to "publishing". Is this something you guys would be interested in?

### CODE REVIEW

**Comment by NickyBobby** [comment]
Hey @dunncl15 it would be cool if you wanted to implement that feature but it's totally not necessary. As far as I'm concerned you're done but if you wanted to keep working on it, I'm totally fine with giving PR code reviews. I've been a little slow the last two days because I'm traveling but generally will have time to review PR's.

**Comment by dunncl15** [comment]
Sounds good @NickyBobby . I'd like to keep working on it when I have time and
submit PRs periodically. I'm traveling for a couple days over my break but
plan to take a look at the preview feature when I get back.

**Comment by NickyBobby** [comment]
Hey Charlie, is this the most up to date version of the project? I just pulled down the `refactor` branch to see what it looked like and I'm getting a fail to compile error. Let me know if you need help with anything.

**Comment by dunncl15** [comment]
@NickyBobby what's the error you're getting? You may need to do a npm install. I was working on this branch yesterday everything was working okay.

**Comment by NickyBobby** [comment]
Yep that was it. I just forgot to do an npm install. Just did and it looks good. What is the react-modal package doing?

**Comment by dunncl15** [comment]
@NickyBobby if you create a test page you should see a new preview button. That will open a react-modal to give you a preview of the page that was just created. I'm still toying with the best place to put the preview button as each "page card" is getting a bit crowded. Let me know what you think!

**Comment by dunncl15** [comment]
@NickyBobby did you have a chance to check out the modal/preview feature?

**Pull request closed without merging**
