### PR TITLE
Add header component and update routing to reflect admin namespace

### PR DESCRIPTION
**Pull request by dunncl15**
@Riizu @NickyBobby I've made some minor adjustments here, but I updated the routing as discussed previously so now the landing page is /admin. I also found an npm package to create a rich text editor called react-rte, which might be cool for formatting the new pages. I've installed it, but haven't played around with it yet. 

Next up: adding new pages to redux store.

### CODE REVIEW

**Comment by NickyBobby** [comment]
This all looks great. I like the new name spacing. I'm guessing once you figure out how to add new pages to the redux store, then we can mock out a home view so you see something when you first visit `/`. Since the pages won't persist at first, we'll want at least a home page place holder until we hook it up to a backend. Also, I think react-rte is gonna be a great addition, I just checked it out briefly. Do you think we'll be able to add in-line images with that package as well?

@Riizu did you have any other comments?

**Comment by rgbatty** [comment]
This all looks very solid to me as well. I agree a placeholder may be valid for the first check-in, but I don't know myself if its really worth the time - being able to set a page as the home page is really a requirement regardless.

One thing I did notice is in regards to the Navigation component - Is it going to be reused for the user-facing and admin-facing pages, or will there be a separate component for each?

I would like to add that I'm really impressed so far with the consistency and cleanliness of the codebase. Keep up the good work!

**Comment by NickyBobby** [comment]
Is this PR ready to be merged? @dunncl15

**Comment by dunncl15** [comment]
@NickyBobby yeah I think it is ready there aren't too many changes with this PR. @Riizu in terms of the navigation I'm thinking the user-facing nav will probably be a separate component that is "built" by the admin and rendered on the user-facing portion of the site. Do you guys agree with that approach?

**Comment by NickyBobby** [comment]
I agree that the user-facing navbar should be built out by the admin and then stored in the redux store in some way. I have a few ideas on how I would do it but I'm curious how you decide to implement it. This PR looks GTM to me so I'll do that now. 👍

**Pull request merged**
