### PR TITLE
New pages added to redux store and rendered on /admin/pages route

### PR DESCRIPTION
**Pull request by dunncl15**
@Riizu @NickyBobby I've added initial functionality for saving a page to the redux store and rendering the saved pages on /admin/pages. My goal for today is to get the edit functionality working using the react-rte package.  Let me know your thoughts when you have a chance!

**Creating a page:**
screen shot 2017-04-12 at 1 33 44 pm

**Saved page**
screen shot 2017-04-12 at 1 33 55 pm

### CODE REVIEW

**Comment by NickyBobby** [comment]
This looks great. I have no problem with having you work on edit functionality for the rest of the day today. Tomorrow let's discuss how we're gonna take the pages from `/admin/pages` to their respective namespacing on the front facing side of the website. I'm assuming this is where the publish button will come into play. Also what was your thinking behind the 'add to navigation' button? Because my thinking was that once you publish a page, it will be automatically added to the navigation bar. Again I think these will be good things to discuss during our check-in tomorrow morning. I'm all good with this being merged unless @Riizu has any objections.

Also what time will work best for you for a check-in tomorrow morning? @dunncl15

**Comment by rgbatty** [comment]
My assumption is "publish" dictates whether the page is actually visible while "add to navigation" adds the relevant link to a nav bar.

I'm also fine with spending the day on edit functionality, though is it currently possible to visit a page directly?

**Comment by dunncl15** [comment]
That was my thought as well @Riizu . The add to navigation button would actually add a new nav link while publishing would mean it's a visible page, but may not be included in the nav bar. Neither is functional so I'm definitely open to other ideas. 

As of now, I haven't created individual pages that you can visit directly. That's next on the list along with editing.

We have work time all day tomorrow so I can meet whenever is convenient for you guys.
@NickyBobby

**Comment by NickyBobby** [comment]
how about we have our check-in at 10 am tomorrow morning. Does that work for everyone? @Riizu @dunncl15 

And in the meantime I'll merge this PR in if you're good with it @dunncl15

**Comment by dunncl15** [comment]
10am works for me @NickyBobby . Talk to you guys then.

**Pull request merged**
